<?php

namespace MariscoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgRepository extends EntityRepository
{
}
