data_index:
    path:     /
    defaults: { _controller: "MariscoBundle:Data:index" }
    methods:  GET

data_show:
    path:     /{id}/show
    defaults: { _controller: "MariscoBundle:Data:show" }
    methods:  GET

data_new:
    path:     /{user}/new
    defaults: { _controller: "MariscoBundle:Data:new" }
    methods:  [GET, POST]

data_edit:
    path:     /{id}/edit
    defaults: { _controller: "MariscoBundle:Data:edit" }
    methods:  [GET, POST]

data_delete:
    path:     /{id}/delete
    defaults: { _controller: "MariscoBundle:Data:delete" }
    methods:  DELETE
