font_productList:
    path:     /productList/{category}
    defaults: { _controller: MariscoBundle:Default:productList }

shop_cart:
    path:     /cart
    defaults: { _controller: MariscoBundle:Default:cart }

cart_addtocartAjax:
    path:     /addtocartAjax
    defaults: { _controller: MariscoBundle:Default:addtocartAjax }

cart_update:
    path:     /cart/updateNum
    defaults: { _controller: MariscoBundle:Default:ajaxUpdate }

cart_cartitem_delete:
    path:     /{id}/cartdelete
    defaults: { _controller: MariscoBundle:Default:cartdelete }