MariscoBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: MariscoBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nameEs:
            type: string
            length: 255
        price:
            type: float
        code:
            type: string
            length: 255
        foto:
            type: string
            length: 255
        isShow:
            type: boolean
        isSale:
            type: boolean
        discountPrice:
            type: float
            nullable: true
        isOferta:
            type: boolean
        maiUnit:
            type: integer
        suanUnit:
            type: integer
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
